### PR TITLE
Add Sonar properties file

### PR DESCRIPTION
**Pull request by ghost**
Adding Sonar properties file for auto-scanning of code quality.

### CODE REVIEW

**Review by BernardoSilva — DISMISSED** [review]
Looking good but no point in adding the file if its all commented out...
Are you planing to add the configurations there?

**Comment by ghost** [comment]
> 
> 
> Looking good but no point in adding the file if its all commented out...
> Are you planing to add the configurations there?

Wondered if you'd notice 😁 fixed.

**Comment by ghost** [comment]
Works:

image

**Review by BernardoSilva — APPROVED** [review]
👍

**Pull request merged**
